/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,jsx,ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'primary':                    '#8ff5ff',
        'primary-dim':                '#00deec',
        'primary-fixed':              '#00eefc',
        'primary-fixed-dim':          '#00deec',
        'primary-container':          '#00eefc',
        'on-primary':                 '#005d63',
        'on-primary-container':       '#005359',
        'on-primary-fixed':           '#003f43',
        'on-primary-fixed-variant':   '#005e64',
        'secondary':                  '#af88ff',
        'secondary-dim':              '#8a4cfc',
        'secondary-fixed':            '#dcc9ff',
        'secondary-fixed-dim':        '#d0b8ff',
        'secondary-container':        '#6001d1',
        'on-secondary':               '#2b0065',
        'on-secondary-container':     '#e1d0ff',
        'on-secondary-fixed':         '#430097',
        'on-secondary-fixed-variant': '#6514d6',
        'tertiary':                   '#69daff',
        'tertiary-dim':               '#00c0ea',
        'tertiary-fixed':             '#00cffc',
        'tertiary-fixed-dim':         '#00c0ea',
        'tertiary-container':         '#00cffc',
        'on-tertiary':                '#004a5d',
        'on-tertiary-container':      '#004050',
        'on-tertiary-fixed':          '#002a35',
        'on-tertiary-fixed-variant':  '#004a5c',
        'background':                 '#0e0e0e',
        'on-background':              '#ffffff',
        'surface':                    '#0e0e0e',
        'surface-dim':                '#0e0e0e',
        'surface-bright':             '#2c2c2c',
        'surface-container-lowest':   '#000000',
        'surface-container-low':      '#131313',
        'surface-container':          '#1a1919',
        'surface-container-high':     '#201f1f',
        'surface-container-highest':  '#262626',
        'surface-variant':            '#262626',
        'surface-tint':               '#8ff5ff',
        'on-surface':                 '#ffffff',
        'on-surface-variant':         '#adaaaa',
        'inverse-surface':            '#fcf8f8',
        'inverse-on-surface':         '#565554',
        'inverse-primary':            '#006a71',
        'outline':                    '#777575',
        'outline-variant':            '#494847',
        'error':                      '#ff716c',
        'error-dim':                  '#d7383b',
        'error-container':            '#9f0519',
        'on-error':                   '#490006',
        'on-error-container':         '#ffa8a3',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg:      '0.25rem',
        xl:      '0.5rem',
        full:    '0.75rem',
      },
      fontFamily: {
        headline: ['Manrope', 'sans-serif'],
        body:     ['Inter', 'sans-serif'],
        label:    ['Inter', 'sans-serif'],
        mono:     ['JetBrains Mono', 'Fira Code', 'monospace'],
      },
    },
  },
  plugins: [],
}
